# Generated by Django 5.1.3 on 2025-02-08 09:30

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
