# Generated by Django 5.1.6 on 2025-02-22 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chatbot_app.document'),
            preserve_default=False,
        ),
    ]
